root = "."
testdata_dir = "samples"
tmp_dir = ".tmp"

[build]
args_bin = []
bin = "./.tmp/nuttyqt"
cmd = "go build -o ./.tmp/nuttyqt ."
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "samples"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
## TODO: This might not be enough? But there's no better way?!
kill_delay = "500ms"
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
