services:

  nuttyqt:
    image: didstopia/nuttyqt:development
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuttyqt
    restart: unless-stopped
    environment:
      - MQTT_BROKER_PROTOCOL=tcp
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT=nuttyqt_dev
      - MQTT_TOPIC=nuttyqt_dev
      - MQTT_USER=
      - MQTT_PASS=
      # - NUT_SERVER=192.168.0.1
      - NUT_SERVER=localhost
      - NUT_PORT=3493
      - NUT_USER=fakeuser
      - NUT_PASS=fakepass
      - NUT_FAKE=true
      - UPDATE_INTERVAL=5
      # - VERBOSE=true
      - VERBOSE=false
    networks:
      - nuttyqt
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2.0.13
    container_name: mosquitto
    restart: unless-stopped
    networks:
      - nuttyqt
    ports:
      - 127.0.0.1:1883:1883
      - 127.0.0.1:9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_logs:/mosquitto/log
      - mosquitto_data:/mosquitto/data

  ## TODO: Create a dummy NUT server for testing purposes

networks:
  nuttyqt:

volumes:
  mosquitto_logs:
  mosquitto_data:
